### ISSUE TITLE
simplify build w/o losing layout plugins?

### ISSUE THREAD

**Issue by paul-shannon** [cytoscape/cyjShiny#29]
See this stackoverflow thread for a description of the problem (high complexity of webpack-based build) and the limits of building from the single cytoscape.js file Max Franz provides:

   https://stackoverflow.com/questions/62417689/simplest-build-system-for-cytoscape-js/62475513#62475513

**Comment by patelaryan7751** [comment]
@paul-shannon actually i am looking closely to this issue can you give some more info on this ?

**Comment by paul-shannon** [comment]
@patelaryan7751 ,  The goal is to create a minimal build system which combines the current cytoscape.js build (for instance, https://github.com/cytoscape/cytoscape.js/blob/master/dist/cytoscape.cjs.js) with other plugins not included in the build.

I want to avoid webpack and npm - because both bring in a huge number of files, require a commitment to a sprawling build system.

We need it small.  Minimal.  Fast. Run out of a makefile.

**Comment by paul-shannon** [comment]
complete.   see ```cyjShiny/inst/htmlwidgets``` and especially the yaml file, and the lib directories.  the htmlwidget builds, run out of R CMD build, neatly assembles all the javascript code into the package.
