### ISSUE TITLE
rmarkdown declaration

### ISSUE THREAD

**Issue by Dharna5599** [cytoscape/cyjShiny#36]
rmarkdown needs to be declared as a soft dependency in the [Description](https://github.com/cytoscape/cyjShiny/blob/master/DESCRIPTION) file. This would not affect existing contributors but the new ones may be affected as previously rmarkdown was guaranteed by knitr but now it is not so. 
[https://github.com/yihui/knitr/issues/1864](https://github.com/yihui/knitr/issues/1864)

**Comment by Dharna5599** [comment]
Possible solution 
Suggestes: rmarkdown
@paul-shannon, may I work on this?

**Comment by paul-shannon** [comment]
absolutely.
