### ISSUE TITLE
bump DESCRIPTION version minor number and date with each commit

### ISSUE THREAD

**Issue by paul-shannon** [cytoscape/cyjShiny#41]
Hi @Dharna5599, 

Currently:
```
Version: 1.0.8
Date: 2021-04-01
```
Good practice is to increment these with each non-trivial commit.    Bioconductor (perhaps CRAN as well) will only do a fresh build and deploy if the version number is incremented.   We are not yet ready to submit, but this practice is useful nonetheless.

**Comment by Dharna5599** [comment]
Sure @paul-shannon,
I will take care of it
