### ISSUE TITLE
shinytest fails to capture nodes and edges

### ISSUE THREAD

**Issue by paul-shannon** [cytoscape/cyjShiny#42]
see ```inst/unitTests/shinyTest_01/tests/shinytest/test_01-expected/*.png```
It is quite likely that this failure has been seen, reported, and maybe addressed by others.
Strategy: 

-  search the web, and RStudio community, for similar reports
- create a new, minimal, tiny shiny app which draws a plot.   does shinytest exhibit the same failure?
- keep me informed of your progress & problems at each step, at least daily

Here is 003.png:

![image](https://user-images.githubusercontent.com/2480712/121049616-b57a0400-c76c-11eb-8c0e-fba52efb1d16.png)

**Comment by Dharna5599** [comment]
Sure @paul-shannon

**Comment by paul-shannon** [comment]
this and other shinytest eccentricities led me to discard shinytest, instead using the approach demonstrated in ```unitTests/test_selection.R```
