### ISSUE TITLE
Do I have an option to load a JSON object directly to cyjShiny?

### ISSUE THREAD

**Issue by gmhhope** [cytoscape/cyjShiny#54]
Hi cyjShiny developers,

It is great to see that cytoscape file can now be rendered to Shiny app. I am so excited.

I used Networkx to get cytoscape-format JSON file and import them directly to cytoscape desktop. So do I have an option to directly load the JSON file in cyjShiny?

Here is one example file: [test.json.zip](https://github.com/cytoscape/cyjShiny/files/11636306/test.json.zip)

Thanks,
Minghao

**Comment by cannin** [comment]
@gmhhope Does this example help? https://github.com/cytoscape/cyjShiny/blob/2103f1c3b23a355756e6c65a8a80c058da5091c7/inst/demos/fromCytoscapeDesktop/app.R#L177

**Comment by gmhhope** [comment]
Thanks very much @cannin! That works!

May I ask another questions: 

(1) Do I have an option to export a style (in desktop) with a particular layout (nodes/edges being positioned using desktop) and then put into the Rshiny App?
(2) I don't see the nodes/edges attributes in the Rshiny app. How to make it happen?

Any references and suggestions that get me oriented to the right places are greatly appreciated!

Thanks,
Minghao Gong

**Comment by cannin** [comment]
The questions might be related. We need to go in parts. First question, have you tried: 

<img width="1299" alt="Screenshot 2023-06-02 at 11 17 19 AM" src="https://github.com/cytoscape/cyjShiny/assets/790284/353cbd7d-37f4-476b-9373-731edaa73336">

**Comment by gmhhope** [comment]
Hmm, it looks like exporting the Cytoscape to NDEx is more straightforward in my case. 

Is there any benefit to using cyjShiny instead of NDEx? No offense but just want to understand more before investing more time in either direction. Appreciate your prompt responses!

Thanks,
Minghao Gong

**Comment by cannin** [comment]
@gmhhope Apologies for the delay. NDEx lets you show a network on the NDEx servers with the functionalities they provide. cyjShiny is if you would want to make interactive tools for yourself and collaborators that you want customized (e.g., perhaps cancer pathways and some analysis you developed): 1) application using R Shiny or 2) include interactive networks as R Markdown notebooks shared as HTML files.

**Comment by gmhhope** [comment]
Thanks for the comments!
