### ISSUE TITLE
`setNodeAttributes` should just call `node.data()`

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cyjShiny#9]
- [ ] Using a selector is slower than `cy.getElementById()`.
- [ ] Use `node.data()` instead of `Object.defineProperty()`.
- [ ] `self.cyj.style().update();` is unncessary.

**Comment by paul-shannon** [comment]
Thanks, Max.   I will make these changes.

**Comment by paul-shannon** [comment]
Done.   package version 0.99.21
@maxkfranz - it  took me a while to figure out I needed to make ````attributeName```` an array.
````
node.data({[attributeName]:  newValue});
````

**Comment by maxkfranz** [comment]
Yes, that's just es6 syntax sugar for this:

```js
let payload = {};

payload[attributeName] = newValue;

node.data(payload);
```
